In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os

print(os.getcwd())

d:\Pendrive\VSCode\Bioinformatics\notebooks

In [3]:
counts = pd.read_csv(
    "../data/raw/GSE60424_GEOSubmit_FC1to11_normalized_counts.txt",
    sep="\t"
)

In [4]:
counts.head()

,genenames,lib221,lib222,lib223,lib224,lib225,lib226,lib227,lib228,lib229,...,lib346,lib347,lib348,lib349,lib350,lib351,lib352,lib353,lib354,lib355
0,ENSG00000000003,1,0,1,1,1,0,0,0,2,...,1,0,1,0,0,0,1,1,0,0
1,ENSG00000000005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000000419,23,22,25,28,25,41,18,12,14,...,28,19,35,37,25,17,22,25,25,30
3,ENSG00000000457,11,11,14,17,11,32,9,24,19,...,18,13,15,26,5,23,17,15,14,14
4,ENSG00000000460,3,3,3,3,2,4,5,9,4,...,11,9,5,4,7,12,8,8,11,5

In [5]:
counts.shape

(50045, 135)

In [6]:
counts.info()

<class 'pandas.DataFrame'>
RangeIndex: 50045 entries, 0 to 50044
Columns: 135 entries, genenames to lib355
dtypes: int64(134), str(1)
memory usage: 51.5 MB

In [7]:
counts.describe()

,lib221,lib222,lib223,lib224,lib225,lib226,lib227,lib228,lib229,lib230,...,lib346,lib347,lib348,lib349,lib350,lib351,lib352,lib353,lib354,lib355
count,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,...,50045.000000,50045.000000,50045.00000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000,50045.000000
mean,22.609811,20.416645,22.204296,18.568568,18.031592,35.974503,23.953202,18.340034,16.302388,18.206374,...,17.667060,13.903267,19.96683,30.438186,20.827076,15.643201,14.999520,16.880827,17.561734,19.049336
std,202.076893,163.340574,189.145843,122.615153,125.902534,337.264033,208.023134,157.914431,122.106600,145.960418,...,150.076741,91.380062,161.21924,297.109314,164.726211,148.432453,109.394214,129.482066,129.682870,147.550731
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,2.000000,1.000000,2.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
max,25656.000000,17215.000000,20526.000000,9921.000000,11774.000000,20990.000000,17443.000000,13702.000000,8783.000000,11408.000000,...,13108.000000,7567.000000,17584.00000,22082.000000,12784.000000,13217.000000,8355.000000,10320.000000,10430.000000,16233.000000

In [8]:
counts.isnull().sum()

genenames    0
lib221       0
lib222       0
lib223       0
lib224       0
            ..
lib351       0
lib352       0
lib353       0
lib354       0
lib355       0
Length: 135, dtype: int64

In [9]:
genes = counts['genenames']

expression = counts.drop(columns='genenames')

In [10]:
expression.to_csv(
    "../data/processed/expression_matrix.csv",
    index=False
)